title: <p align="center"> Ahmad Alismail </p>

logo: "/images/IMG_0320.PNG?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ahmadalismail1/">LinkedIn</a> |
  <a href="https://github.com/ahmad-alismail">GitHub</a>
  </p>
  
  <p align="justify">
  Junior Data Scientist | Business Informatics M.Sc.
  <br><br>
  Data scientist with a strong passion for NLP language models and data visualization. A Lifelong learner and equipped with a diverse promising skill set. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
