title: <p align="center"> Ahmad Alismail </p>

logo: "/images/IMG_0320.PNG?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ahmadalismail1/">LinkedIn</a> |
  <a href="https://github.com/ahmad-alismail">GitHub</a>
  </p>
  
  <p align="justify">
  Junior Data Scientist | Business Informatics M.Sc.
  <br><br>
  I'm a data science enthusiast who's passionate about using data-driven approaches to solve real-world problems. I specialize in NLP language models and data visualization, and I'm committed to lifelong learning to continuously expand my skill set.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
