title: <p align="center"> Ahmad Alismail </p>

logo: "/images/IMG_0320.PNG?raw=true"

description:
  <p align="center">
  <a href="pdf/AHA_CV.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ahmadalismail1/">LinkedIn</a> |
  <a href="https://github.com/ahmad-alismail">GitHub</a> |
  <a href="https://medium.com/@ahmadalismail">Medium</a>
  </p>
  
  <p align="justify">
  Junior Data Scientist | Business Informatics M.Sc.
  <br><br>
  a Data Scientist with foundational expertise in Natural Language Processing (NLP), passionate about generative models as a means to enhance human creative processes. Deeply interested in AI security and safety. 
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
